function functie(E_plus,E_minus,R1, R2, A, f, Offset, N, check, semnal)

%%figura2
if (check  == 1)
figure('Name','AMPLIFICATOARE OPERATIONALE IN CONFIGURATIE CU REACTIE NEGATIVA, NEINVERSOARE',...
    'Units','normalized',...
    'Position',[0.025 0.05 0.95 0.85],...
    'NumberTitle','off','color',[0.35 0.2 0.3]);
end
    

%%titlul figurii 2
uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.32 0.88 0.4 0.09],...
          'backgroundcolor', 'w',...
          'foregroundcolor','black',...
          'fontweight', 'bold',...
          'fontsize', 14,...
          'String','AMPLIFICATOARE OPERATIONALE IN CONFIGURATIE CU REACTIE NEGATIVA, NEINVERSOARE');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5
%%caracteristiicle generale ale circuitului-CHENAR1
RadioGroup1=uibuttongroup('Visible','on',...
        'BackgroundColor',[0.78824 0.70196 0.8902],...
        'ForegroundColor','black',...
        'Title','CARACTERISTICILE CIRCUITULUI',...
        'FontSize',11,...
        'FontWeight','Bold',...
        'Position',[0.01 0.5 0.2 0.35],...
        'TitlePosition','centertop',...
        'Tag','radiobutton');
    
  %%tipul circuitului
uicontrol('Style','Text',...
         'Units','normalized',...
         'Position',[0.007 0.75 0.6 0.2],...
         'backgroundcolor',[0.78824 0.70196 0.8902],...
         'foregroundcolor','black',...
         'FontSize',11,...
         'String','Tipul circuitului:',...
         'Parent',RadioGroup1);
     
uicontrol('Style','Text',...  
        'Units','normalized', ...
        'Position',[0.08 0.70 0.6 0.1],...
        'FontSize' ,9,...
        'String','neinversor',...
        'Parent', RadioGroup1); 
  
%%obiectele text si edit pt tensiunea de alimentare   
uicontrol('Style','text',...
         'Units','normalized',...
         'Position',[0.079 0.55 0.2 0.1],...
         'backgroundcolor','w',...
         'foregroundcolor','black',...
         'String','+E[V] = ',...
         'FontSize',11,...
         'Parent', RadioGroup1);
uicontrol('Style','edit',...
         'Units','normalized',...
         'Position',[0.3 0.55 0.2 0.1],...
         'foregroundcolor','b',...
         'String',E_plus,...
         'Callback','E_plus=str2num(get(gco,''String''));functie(E_plus,E_minus,R1, R2, A, f, Offset, N, check, semnal)',...
         'Parent', RadioGroup1);
     uicontrol('Style','text',...
         'Units','normalized',...
         'Position',[0.52 0.55 0.2 0.1],...
         'backgroundcolor','w',...
         'foregroundcolor','black',...
         'String','-E[V] = ',...
         'FontSize',11,...
         'Parent', RadioGroup1);
uicontrol('Style','edit',...
         'Units','normalized',...
         'Position',[0.72 0.55 0.2 0.1],...
         'foregroundcolor','b',...
         'String',E_minus,...
         'Callback','E_minus=str2num(get(gco,''String''));functie(E_plus,E_minus,R1, R2, A, f, Offset, N, check, semnal)',...
         'Parent', RadioGroup1);
    
%obiectele text si edit pentru cele 2 rezistente
uicontrol('Style','text',...
         'Units','normalized',...
         'Position',[0.065 0.38 0.5 0.1],...
         'backgroundcolor','w',...
         'foregroundcolor','black',...
         'String','R1[sute kohm] = ',...
         'FontSize',11,...
         'Parent', RadioGroup1);
 uicontrol('Style','edit',...
         'Units','normalized',...
         'Position',[0.55 0.38 0.41 0.1],...
         'foregroundcolor','b',...
         'String',R1,...
         'Callback','R1 = str2num(get(gco,''String''));functie(E_plus,E_minus,R1, R2, A, f, Offset, N, check, semnal)',...
          'Parent', RadioGroup1);
uicontrol('Style','text',...
         'Units','normalized',...
         'Position',[0.065 0.21 0.5 0.1],...
         'backgroundcolor','w',...
         'foregroundcolor','black',...
         'String','R2[sute kohm] = ',...
         'FontSize',11,...
         'Parent', RadioGroup1);
uicontrol('Style','edit',...
         'Units','normalized',...
         'Position',[0.55 0.21 0.41 0.1],...
         'foregroundcolor','b',...
         'String',R2,...
        'Callback','R2 = str2num(get(gco,''String''));functie(E_plus,E_minus,R1, R2, A, f, Offset, N, check, semnal)',...
         'Parent', RadioGroup1);
     
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  
 uicontrol('Style','text',...
         'Units','normalized',...
         'Position',[0.065 0.11 0.55 0.09],...
         'backgroundcolor','red',...
         'foregroundcolor','w',...
         'FontWeight','bold',...
         'String','Serii de valori standartizate',...
         'FontSize',9,...
         'Parent', RadioGroup1);
 % index = 1;
  %uicontrol('Style','PopupMenu',...
 %'Units','normalized',...
 %'Position',[0.63 0.11 0.37 0.09],...
 %'String','seria12|seria6',...
 %'Value', index,...
 %'Parent', RadioGroup1,...
 %'Callback','index=get(gco,''value'');functie(E_plus,E_minus,R1, R2, A, f, Offset, N, Gain, check)');

%if index ==1
 % open ('C:\Users\Admin\Documents\MATLAB\seria12.pdf');
%end
%if index == 2
 %   open('C:\Users\Admin\Documents\MATLAB\seria_24.pdf')
%end
     
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5
 %%CREAM CHENARUL UNDE STABILIM CARACTERISTICILE SEMNALULUI
RadioGroup2 = uibuttongroup('Visible','on',...
        'BackgroundColor','[0.78824 0.70196 0.8902]',...
        'ForegroundColor','black',...
        'Title','CARACTERISTICILE semnalului',...
        'FontSize',11,...
        'FontWeight','Bold',...
        'TitlePosition','centertop',...
        'Position',[0.54 0.5 0.2 0.35],...
        'Tag','radiobutton');
 

  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%55   
 %Parametrii semnalului de intrare
 
 %Amplitudinea
 uicontrol('Style','text',...
         'Units','normalized',...
         'Position',[0.25 0.7 0.2 0.1],...
         'backgroundcolor','w',...
         'foregroundcolor','black',...
         'String','A[V] = ',...
         'FontSize',12,...
         'Parent', RadioGroup2);
 uicontrol('Style','edit',...
         'Units','normalized',...
         'Position',[0.55 0.7 0.2 0.1],...
         'foregroundcolor','b',...
         'String', A,...
         'Callback','A=str2num(get(gco,''String''));functie(E_plus,E_minus,R1, R2, A, f, Offset, N, check, semnal)',...
         'Parent', RadioGroup2);
     
 %Offset
 uicontrol('Style','text',...
         'Units','normalized',...
         'Position',[0.25 0.55 0.2 0.1],...
         'backgroundcolor','w',...
         'foregroundcolor','black',...
         'String','Offset = ',...
         'FontSize',12,...
         'Parent', RadioGroup2);
 uicontrol('Style','edit',...
         'Units','normalized',...
         'Position',[0.55 0.55 0.2 0.1],...
         'foregroundcolor','b',...
         'String',Offset,...
         'Callback','Offset=str2num(get(gco,''String''));A=str2num(get(gco,''String''));functie(E_plus,E_minus,R1, R2, A, f, Offset, N, check, semnal)',...
         'Parent', RadioGroup2);
     
 %numarul de perioade N pe care reprezentam forma de unda de intrare
 uicontrol('Style','text',...
     'Units','normalized',...
     'Position',[0.25 0.1 0.2 0.1],...
     'backgroundcolor','w',...
     'foregroundcolor','black',...
     'String','N = ',...
     'FontSize',12,...
     'Parent', RadioGroup2);
 uicontrol('Style','edit',...
         'Units','normalized',...
         'Position',[0.55 0.1 0.2 0.1],...
         'String',N,...
         'Callback','N=str2num(get(gco,''String''));E_plus=str2num(get(gco,''String''));close;functie(E_plus,E_minus,R1, R2, A, f, Offset, N, check, semnal)',...
         'Parent', RadioGroup2);

 %un slider pentru a selecta frecventa
 uicontrol('Style','text',...
         'Units','normalized',...
         'Position',[0.25 0.4 0.2 0.1],...
         'backgroundcolor','w',...
         'foregroundcolor','black',...
         'String','f[Hz] = ',...
         'FontSize',12,...
         'Parent', RadioGroup2);
 Bs=uicontrol('Style','slide',...
         'Units','normalized',...
         'Position',[0.6 0.4 .3 .1],...
         'Min',50,'Max',20000,'Value',f,...
         'Callback','f=round(get(gco,''Value''));close;functie(E_plus,E_minus,R1, R2, A, f, Offset, N, check, semnal)',...
         'Parent', RadioGroup2) ;
 uicontrol('Style','text',...
         'Units','normalized',...
         'Position',[0.56 0.4 0.04 0.1],...
         'backgroundcolor','blue',...
         'foregroundcolor','black',...
         'String',num2str(get(Bs,'Min')),...
         'Parent', RadioGroup2);
 uicontrol('Style','text',...
         'Units','normalized',...
         'Position',[0.9 0.4 0.05 0.1],...
         'backgroundcolor','blue',...
         'foregroundcolor','black',...
         'String',num2str(get(Bs,'Max')),...
         'Parent', RadioGroup2);
  uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.6 0.25 0.2 0.1],...
        'foregroundcolor','black',...
        'String',f,...
        'Parent', RadioGroup2);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Adaugam si afisam schema electrica a circuitului
x = imread('C:\Users\Admin\Documents\MATLAB\AO_neinversor.png'); %%citirea imaginii
image(x); %%afisarea imaginii
set(gca,'position',[0.24 0.53 0.27 0.32]);
axis off;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5
%%calculam perioada semnalului

T = 1/f;
 uicontrol('Style','text',...
     'Units','normalized',...
     'Position',[0.75 0.72 0.07 0.03],...
     'backgroundcolor',[0.78824 0.70196 0.8902],...
     'foregroundcolor','black',...
     'String','T = 1/f = ',...
     'FontSize',13);
 uicontrol('Style','edit',...
         'Units','normalized',...
         'Position',[0.83 0.72 0.07 0.03],...
         'backgroundcolor',[0.78824 0.70196 0.8902],...
         'foregroundcolor','black',...
         'Callback','T=str2num(get(gco,''String''));functie(E_plus,E_minus,R1, R2, A, f, Offset, N, check, semnal)',...
         'String',T,...
         'FontSize',13);
     
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5
%%valoarea castigului in tensiune si a tensiunii de iesire maxime=GAIN

    Gain = 1 + R2/R1;
 uicontrol('Style','text',...
     'Units','normalized',...
     'Position',[0.75 0.76 0.05 0.03],...
     'backgroundcolor',[0.78824 0.70196 0.8902]	,...
     'foregroundcolor','black',...
     'String','Gain = ',...
     'FontSize',11);
 uicontrol('Style','edit',...
         'Units','normalized',...
         'Position',[0.81 0.76 0.05 0.03],...
         'backgroundcolor',[0.78824 0.70196 0.8902],...
         'foregroundcolor','black',...
         'String', Gain,...
         'FontSize',11,...
         'Callback','Gain = str2num(get(gco,''String''));functie(E_plus,E_minus,R1, R2, A, f, Offset, N, check, semnal)');
  
     
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %setam tensiunea de iesire maxima a amplificatorului in RN
     Vo_Max = Gain * A;
       uicontrol('Style','text',...
         'Units','normalized',...
         'Position',[0.75 0.8 0.15 0.05],...
         'backgroundcolor','[0.96863 0.84706 0.65882]',...
         'foregroundcolor','r',...
         'String','!!!!Vo_Max  = ',...
         'FontSize',14);
 uicontrol('Style','edit',...
         'Units','normalized',...
         'Position',[0.91 0.8 0.07 0.05],...
         'backgroundcolor',[0.96863     0.84706     0.65882],...
         'foregroundcolor','r',...
         'String',Vo_Max,...
         'FontSize',14,...
         'Callback','Vo_Max = str2num(get(gco,''String''));closefunctie(E_plus,E_minus,R1, R2, A, f, Offset, N, check, semnal)');
     
     
         
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%foia de catalog specificatii TL081
 RadioGroup3 = uibuttongroup('Visible','on',...
    'BackgroundColor','r',...
    'ForegroundColor','black',...
    'Title','Specificatii pentru TL081',...
    'FontSize',13,...
    'FontWeight','Bold',...
    'TitlePosition','centertop',...
    'Position',[0.75 0.4 0.23 0.19],...
    'Tag','radiobutton');
     
%Curentul de iesire maxim
 uicontrol('Style','text',...
     'Units','normalized',...
     'Position',[0.1 0.75 0.7 0.17],...
     'backgroundcolor','w',...
     'foregroundcolor','black',...
     'String','Ios = 40 mA, pt temp = 25C',...
     'FontSize',12, ...
     'Parent', RadioGroup3);
 
 %Valoarea slew rate 
   uicontrol('Style','text',...
     'Units','normalized',...
     'Position',[0.1 0.5 0.7 0.15],...
     'backgroundcolor','w',...
     'foregroundcolor','black',...
     'String','SR = 16 V/us',...
     'FontSize',12, ...
      'Parent', RadioGroup3);
  
 


     uicontrol('Style','PopupMenu',...
                            'Units','normalized',...
                            'Position',[0.25 0.87 0.5 0.09],...
                            'value',semnal,...
                            'FontSize',11,...
                            'FontWeight','bold',...
                            'foregroundColor','black',...
                            'backgroundColor','w',...
                            'String','Sinusoidal|Triunghiular',...
                             'Parent', RadioGroup2,...
                            'Callback','semnal=get(gco,''value'');close;functie(E_plus,E_minus,R1, R2, A, f, Offset, N, check, semnal)');
t=0:T/100:N*T;


%%%%%%%%%%%%%%%%%%Tipuri semnal
if semnal==1   %%semnal sinusoidal
    vi=Offset+A*sin(2.*3.14.*f*t);
    vo=Gain*vi;
    
end
if semnal==2     %%semnal triunghiular
    vi=Offset+(2*A/pi)*asin(sin(2.*3.14.*f*t));
    vo=Gain*vi;
    

end

%%%%limitarea tensiunii de iesire
k=max(size(t));
for i=1:k
    if (vo(i)>E_plus) 
        vo(i)=E_plus;
    end
    if (vo(i)<E_minus)
        vo(i)=E_minus; 
    end
end

%--Vi--
subplot(245)
plot(t,vi,'g'); %g-verde(culoarea la linia de pe grafic)
grid on;
title('Reprezentarea semnalului de intrare');
xlabel('t[s]','color', 'w');
ylabel('Amplitudinea[V]','color', 'w');

%--Vo--
subplot(246)
plot(t,vo,'r'); %rosu
grid on;
title('Reprezentarea semnalului de iesire');
xlabel('t[s]', 'color', 'w');
ylabel('Amplitudinea[V]','color', 'w');

ylim([E_minus-A-2 E_plus+A+2]);

%%%%%%%%%%%%%%%%%CSTV
 Ph=max(vi); %Calcul valorii maxime a semnalului Vi
 Pl=min(vi);
subplot('position',[0.55 0.1 0.4 0.25]);
plot(vi,vo,'-r');
hold on;
grid on;
axis([Pl-2 Ph+2 E_minus-2 E_plus+2])

title('Caracteristica statica de transfer in tensiune [CSTV]','FontSize',15,'color','black');
xlabel('[ Vi ]','color','w');
ylabel('[ Vo ]','color','w');   


%%%%%%%%%%%%%%Repetor de tensiune-
      
 if(Gain==1)
     
   uicontrol('Style','text',... 
'Units','normalized',...
'Position',[0.25 0.49 0.2 .03],...
'FontWeight','bold',...
'Fontsize',12,...
'backgroundcolor','w',...
'foregroundcolor','black',...
'string','Repetor de tensiune neinversor');
 end
 


  

end

