
close all;
clc;

Fig=figure('Name','AO cu reactie negativa',...
           'Units','normalized',...
           'Position',[0.1 0.1 0.8 0.8],...
           'NumberTitle','off',...
           'color', '[0.55 0.6 0.8]');
       
%Amplificatoare operationale in configuratie cu reactie negativa, neinversoare
%Rusu Ana-Maria, grupa 2123, seria A, anul II
       
%%importam si afisam fisier de tip png       
a=imread('C:\Users\Admin\Documents\MATLAB\prim_pag.png');
image(a);
set(gca,'position',[0.15 0.23 0.6 0.55]);
axis off;



%Setam parametrii de intrare a circuitului
E_plus = 15;
E_minus = -15;
N = 3;
A = 3;
f = 1000;
Offset = 0;
check = 0;
semnal = 1;

R1 =1;
R2 = 6;
Gain = 1 + R2/R1;

%%%%%%%%%%%%%%%%%%%%% Meniu
fig=uimenu('Label','Proiect');
uimenu(fig,'Label','Documentatie','Callback','Documentatie');% Teorie
uimenu(fig,'Label','Prezentare','Callback','Prezentare');% Prezentare
uimenu(fig,'Label','Close','Callback','close',...
'Separator','on','Accelerator','Q');

uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.8 0.5 0.19 0.1],...
    'FontSize',12,...
    'backgroundcolor','w',... 
    'foregroundcolor',[0.4940, 0.1840, 0.5560],... 
    'FontWeight','bold',...
    'FontName','Comic Sans MS',...
    'String','Documentatie',...
    'Callback','Documentatie;');

uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.8 0.35 0.19 0.1],...
    'FontSize',12,...
    'backgroundcolor','w',... 
    'foregroundcolor',[0.4940, 0.1840, 0.5560],... 
    'FontWeight','bold',...
    'FontName','Comic Sans MS',...
    'String','Prezentare',...
    'Callback','Prezentare;');

uicontrol('Style','text',... 
          'Units','normalized',... 
          'Position',[0.25 0.85 0.4 0.1],... 
          'FontWeight','bold',...
          'FontName','Comic Sans MS',...
          'FontSize',20,...
          'backgroundcolor',[1 1 1],... 
          'foregroundcolor',[0.4940, 0.1840, 0.5560],...
          'String','AO IN CONFIGURATIE CU REACTIE NEGATIVA, NEINVERSOR'); 
uicontrol('Style','text',... 
          'Units','normalized',... 
          'Position',[0.8 0.65 0.19 0.08],... 
          'FontWeight','bold',...
          'FontName','Comic Sans MS',...
          'FontSize',12,...
          'backgroundcolor','w',... 
          'foregroundcolor',[0.4940, 0.1840, 0.5560],... 
          'String',' Rusu Ana-Maria, Grupa 2123');


%%%open
uicontrol('Style','pushbutton',... 
          'Units','normalized',... 
          'Position',[0.3 0.05 0.3 0.12],... 
          'FontWeight','bold',...
          'Value', check,...
          'FontName','Comic Sans MS',...
          'FontSize',13,...
          'foregroundcolor',[0.4940, 0.1840, 0.5560],... 
          'String','Amplificator operational neinversor',...
          'Callback','check = get(gco, ''Value''); close;functie(E_plus,E_minus,R1, R2, A, f, Offset, N, check, semnal)');
      
uicontrol('Style', 'pushbutton', ...
        'Units', 'normalized',...
        'position', [0.83 0.07 0.1 0.05],...
        'FontWeight','bold',...
        'FontName','Comic Sans MS',...
        'FontSize',10,...
        'foregroundcolor','b',... 
        'string' ,'INCHIDE',...
        'callback', 'close'); 
    